name: Docker Image CI (Github Registry)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and Push the image to ghcr
      run: |
        docker build . --file Dockerfile --tag ghcr.io/mujtabaidrees94/plurality-backend-api-ghcr:latest
        docker login --username ${{ secrets.GHCR_USERNAME }} --password ${{ secrets.GHCR_TOKEN }} ghcr.io
        docker push ghcr.io/mujtabaidrees94/plurality-backend-api-ghcr:latest
